### ISSUE TITLE
你的笔记本显卡是1050的还是1060的，hdmi可以外接显示器？

### ISSUE THREAD

**Issue by Clago** [KangJinChen/Hackintosh-Lenovo-R720#1]
1060款的hdmi输出应该是独显的。
难道1050款的输出不是独显？

**Comment by KangJinChen** [comment]
1050ti的，N卡的独显在10.14版本都无法驱动，webdriver驱动被苹果卡住了，HDMI输出正常。

**Comment by wws0516** [comment]
您好，请问是怎么驱动HDMI输出的，相同笔记本，13.4版本，但是HDMI插上外接显示器没反应？

**Comment by Clago** [comment]
> 您好，请问是怎么驱动HDMI输出的，相同笔记本，13.4版本，但是HDMI插上外接显示器没反应？

你是1050还是1060，1060是无法驱动，因为hdmi走独显输出了。如果是1050系列，你就装macOS Mojave，然后用这个驱动应该就行了吧。
